### ISSUE TITLE
php 7.2 sess_write() does not get called 

### ISSUE THREAD

**Issue by daviddpd** [opennetadmin/ona#130]
I cannot get adodb_sessions to work with php 7.2.  File based sessions do work ( of course with #129 ). 

I've tried various debugging statements and such, and to the best I can find sess_write() is never getting called, so the sessions never gets inserted into the database.  Reverting to PHP 5.6 and sessions then start working.

**Comment by romano80** [comment]
I have the same problem the user is authenticated but doesn't have permission and session table no have records

**Comment by mattpascoe** [comment]
I've not yet tested ONA on anything higher than PHP 7.0.28... Looks like I need to update a few things.

I'll have a look into this.  Thanks for the heads up

**Comment by framer99** [comment]
I've got this figured out, the custom handler sess_read() returns "false" if the session did not exist (first page load).
In PHP<7.1 session_start() will still initialize the $_SESSION var when sess_read() returns false, but 7.1 no longer does.
See the changelog here:
    [http://php.net/manual/en/function.session-start.php](http://php.net/manual/en/function.session-start.php)

Explained here also:
    [http://php.net/manual/en/function.session-start.php#120589](http://php.net/manual/en/function.session-start.php#120589)

The fix is to just return an empty string ' ' instead of false.

My debugging to ona.log showed that open(),read(), and close were called, but never write() as others pointed out. Since PHP never initialized $_SESSION, it makes sense it would never write it, but it seems like the ona code would have populated some part of $_SESSION and it would then exist to be written at close. Although, I never looked and maybe in the ona code it's usage is all conditional on whether $_SESSION already exists?

Or possibly more likely, PHP just ignores $_SESSION for the life of the script since it did not initialize it. So, $_SESSION just works as any other use declared variable and does not get passed to sess_write() ( sess_write() never even gets called)

I'm working on a pull request hopefully today.
