### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by Uzzi** [opennetadmin/ona#145]
Hi this is my system:
Debian 10
MariaDB 10.3.15
PHP 7.3

Are these software versions supported?

**Comment by mattpascoe** [comment]
I have not specifically tested these versions but they should work.  I would recommend that you run the /install/installcli.php tool instead of the web installer.

You also may need to use the dev branch as well.  There are a few things I'm testing there that could impact your install on these newer systems.  Let me know if that does not work and I can dig into it.

**Comment by mattpascoe** [comment]
Closing as I've not heard back on if it worked.. Again, it should work just fine under the develop branch at least.
